### ISSUE TITLE
What is bonsai mode for?

### ISSUE THREAD

**Issue by AdiWeit** [Laubersheini/johnny#4]
As far as I can tell, changing to bonsai mode deletes some of the macro code and uses `db --> acc` instead of` acc:= 0` and `plus`, which by the way should be the default in my opinion because it is one step less and easier to understand. 
So what should you use bonsai mode for? It feels like it doesn't really change anything.

**Comment by Laubersheini** [comment]
The "bonsai mode" gives the same instruction set as another model computer The "bonsai computer" https://www.inf-schule.de/rechner/bonsai/cpu (german link).

Essentially these are the minimum instructions needed to be Turing complete. It can be used to demonstrate, that for example the ability to add to numbers can be emulated by repeatedly incrementing and decrementing.

I hope this answers your question regarding the Bonsai mode
